services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ~/app/volumes/crystall_puzzles:/app
    networks:
      - backend

networks:
  backend:
    name: app_backend
    external: true
