name: Deploy master to server

env:
  MASTER_DIR: ~/app/servers/crystal_puzzles

on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "${{ env.MASTER_DIR }}"

  build:
    runs-on: ubuntu-latest
    needs: upload

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ env.MASTER_DIR }}
            if [ -f "docker-compose.yml" ]; then
              sudo docker compose down --remove-orphans
              sudo docker compose up -d --build
            fi